name: Greeting from Marky

on:

push:
branshes:
- main
jobs:
    build:

    runs-on: ubuntu-latest

    steps:

         - name: checkout repo
         uses: actions/checkout@v2

         - name: Print message

         run: |
         echo "hello world, this a sample CI/CD"
         
